#%RAML 1.0 DataType
properties:
  linha_digitavel:
    type: string
    required: false
    description: código do boleto para ser digitado para pagamento
    example: "1892937971002937871927018038718729"
  link_download:
    type: string
    required: false
    description: link para download do boleto
    example: "https://www.juno.com/boleto/179389"
