#%RAML 1.0 DataType
properties:
  valor_pago:
    type: number
    required: false
    description: valor do pagamento
    example: 18792.00
  data:
    type: datetime-only
    required: false
    description: data do pagamento
    example: "2020-10-29T00:00:00"
